owner: diegosimao
repo: GoverTree---Status

sites:
  - name: GoverTree (App)
    url: https://govertree.com

status-website:
  cname: status.govertree.com
  name: GoverTree — Status
  introTitle: "**Status do GoverTree**"
  introMessage: Página de status em tempo real do GoverTree, monitorada a cada 5 minutos.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
